version: '3'

services:
  web:
    container_name: rtlm_site
    restart: always
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - /etc/letsencrypt/live/rtlm.info/fullchain.pem:/usr/src/app/cert/fullchain.pem
      - /etc/letsencrypt/live/rtlm.info/privkey.pem:/usr/src/app/cert/privkey.pem
    ports:
      - "443:443"
      #- "8000:8000"
    environment:
      - DEBUG=1